// Generated by typings
// Source: node_modules/aurelia-pal-browser/dist/commonjs/aurelia-pal-browser.d.ts
declare module 'aurelia-pal-browser' {
  import {
    initializePAL
  } from 'aurelia-pal';
  
  /**
  * Initializes the PAL with the Browser-targeted implementation.
  */
  export function initialize(): void;
}