//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RjamSoft.Tamil.Grammar.Prosody.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProsodyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProsodyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RjamSoft.Tamil.Grammar.Prosody.Infrastructure.Resources.ProsodyResources", typeof(ProsodyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MenYappu.
        /// </summary>
        public static string AboutMenYappu {
            get {
                return ResourceManager.GetString("AboutMenYappu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenYappu is a website that has all the services essential for poem writers like spell checker/corrector, prosody games, poem composer and poem analyzer integrated and presented in a very simple, intuitive user interface. Since the services are also exposed as web services, mobile phone users can write an app in their preferred platforms like Apple IOS, Android or Windows Mobile usiing these web services and consume them..
        /// </summary>
        public static string AboutMenYappuDetails {
            get {
                return ResourceManager.GetString("AboutMenYappuDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliteration.
        /// </summary>
        public static string Alliteration {
            get {
                return ResourceManager.GetString("Alliteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliteration Type.
        /// </summary>
        public static string AlliterationType {
            get {
                return ResourceManager.GetString("AlliterationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliteration word.
        /// </summary>
        public static string AlliterationWord {
            get {
                return ResourceManager.GetString("AlliterationWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asiriyappaa.
        /// </summary>
        public static string Asiriyappaa {
            get {
                return ResourceManager.GetString("Asiriyappaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asiriyappaavinam.
        /// </summary>
        public static string Asiriyappaavinam {
            get {
                return ResourceManager.GetString("Asiriyappaavinam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Bogdan Urs.
        /// </summary>
        public static string BogdanUrs {
            get {
                return ResourceManager.GetString("BogdanUrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Answer.
        /// </summary>
        public static string CheckAnswer {
            get {
                return ResourceManager.GetString("CheckAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button for help.
        /// </summary>
        public static string ClickThisButtonForHelp {
            get {
                return ResourceManager.GetString("ClickThisButtonForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon....
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with Venpaa rules.
        /// </summary>
        public static string CompareWithVenpaaRules {
            get {
                return ResourceManager.GetString("CompareWithVenpaaRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to contribute content to MenYappu? That&apos;s great! Send us an email and we will get back to you as soon as possible!.
        /// </summary>
        public static string ContributeToMenyappu {
            get {
                return ResourceManager.GetString("ContributeToMenyappu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Duration Count.
        /// </summary>
        public static string CorrectDurationCount {
            get {
                return ResourceManager.GetString("CorrectDurationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of Metrical Lines.
        /// </summary>
        public static string CountOfMetricalLines {
            get {
                return ResourceManager.GetString("CountOfMetricalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not parse initial vowels or short-i before short-u.
        /// </summary>
        public static string DoNotParseShortUBeforeInitialVowels {
            get {
                return ResourceManager.GetString("DoNotParseShortUBeforeInitialVowels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Count.
        /// </summary>
        public static string DurationCount {
            get {
                return ResourceManager.GetString("DurationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminate Vilaankaay Metrical Feet.
        /// </summary>
        public static string EliminateVilaankaayMetricalFeet {
            get {
                return ResourceManager.GetString("EliminateVilaankaayMetricalFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Rhyme.
        /// </summary>
        public static string EndRhyme {
            get {
                return ResourceManager.GetString("EndRhyme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Rhyme Type.
        /// </summary>
        public static string EndRhymeType {
            get {
                return ResourceManager.GetString("EndRhymeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Rhyme word.
        /// </summary>
        public static string EndRhymeWord {
            get {
                return ResourceManager.GetString("EndRhymeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Duration Count and click on &quot;Check Answer&quot; button to see the &quot;Result&quot;. .
        /// </summary>
        public static string EnterDurationCountAndCheckResult {
            get {
                return ResourceManager.GetString("EnterDurationCountAndCheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executor.
        /// </summary>
        public static string Executor {
            get {
                return ResourceManager.GetString("Executor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out more.
        /// </summary>
        public static string FindOutMore {
            get {
                return ResourceManager.GetString("FindOutMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First word.
        /// </summary>
        public static string FirstWord {
            get {
                return ResourceManager.GetString("FirstWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games for Kids and Adults.
        /// </summary>
        public static string GameForKidsAndAdults {
            get {
                return ResourceManager.GetString("GameForKidsAndAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar games are designed with a goal to incrementally learn and advance to the next level in Tamil grammar..
        /// </summary>
        public static string GamesForKidsAndAdultsDescription {
            get {
                return ResourceManager.GetString("GamesForKidsAndAdultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you enter the answer(s), click on &quot;Check Answer&quot; button to see the &quot;Result&quot;..
        /// </summary>
        public static string HowToSeeTheResult {
            get {
                return ResourceManager.GetString("HowToSeeTheResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out cool stuff about the longest surviving classical language in the world and boost your knowledge!.
        /// </summary>
        public static string ImproveKnowledge {
            get {
                return ResourceManager.GetString("ImproveKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Metrical Line (requires atleast 2 Metrical Feet).
        /// </summary>
        public static string InputMetricalLine {
            get {
                return ResourceManager.GetString("InputMetricalLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input only one Metrical Foot.
        /// </summary>
        public static string InputOnlyOneMetricalFoot {
            get {
                return ResourceManager.GetString("InputOnlyOneMetricalFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a sentece (requires at least 2 Metrical Feet).
        /// </summary>
        public static string InputSentence {
            get {
                return ResourceManager.GetString("InputSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Verse.
        /// </summary>
        public static string InputTheVerse {
            get {
                return ResourceManager.GetString("InputTheVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Word.
        /// </summary>
        public static string InputWord {
            get {
                return ResourceManager.GetString("InputWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiration/Motivation.
        /// </summary>
        public static string InspirationAndMotivation {
            get {
                return ResourceManager.GetString("InspirationAndMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalippaa.
        /// </summary>
        public static string Kalippaa {
            get {
                return ResourceManager.GetString("Kalippaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalippaavinam.
        /// </summary>
        public static string Kalippaavinam {
            get {
                return ResourceManager.GetString("Kalippaavinam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Kandasamy Palanisamy.
        /// </summary>
        public static string KandasamyPalanisamy {
            get {
                return ResourceManager.GetString("KandasamyPalanisamy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Get In Touch!.
        /// </summary>
        public static string LetsGetInTouch {
            get {
                return ResourceManager.GetString("LetsGetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Type Finder.
        /// </summary>
        public static string LetterTypeFinder {
            get {
                return ResourceManager.GetString("LetterTypeFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either enter only one word (or) click on &quot;Sample&quot; button below..
        /// </summary>
        public static string LetterTypeFinderInfoTip {
            get {
                return ResourceManager.GetString("LetterTypeFinderInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Types.
        /// </summary>
        public static string LetterTypes {
            get {
                return ResourceManager.GetString("LetterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkage.
        /// </summary>
        public static string Linkage {
            get {
                return ResourceManager.GetString("Linkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkage Finder.
        /// </summary>
        public static string LinkageFinder {
            get {
                return ResourceManager.GetString("LinkageFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkage Type.
        /// </summary>
        public static string LinkageType {
            get {
                return ResourceManager.GetString("LinkageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input only 2 Metrical Feet (or) click on &quot;Sample&quot; button below..
        /// </summary>
        public static string LinkageTypeInfoTip {
            get {
                return ResourceManager.GetString("LinkageTypeInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkage Types.
        /// </summary>
        public static string LinkageTypes {
            get {
                return ResourceManager.GetString("LinkageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with Love and Passion for Tamil.
        /// </summary>
        public static string MadewithLoveAndPassion {
            get {
                return ResourceManager.GetString("MadewithLoveAndPassion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We made this learning portal with love and passion for our language &quot;Tamil&quot;.
        /// </summary>
        public static string MadewithLoveAndPassionDescription {
            get {
                return ResourceManager.GetString("MadewithLoveAndPassionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathirai Calculator.
        /// </summary>
        public static string MathiraiCalculator {
            get {
                return ResourceManager.GetString("MathiraiCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter only one word (or) sentence (or) click on &quot;Sample&quot; button below..
        /// </summary>
        public static string MathiraiCalculatorInfoTip {
            get {
                return ResourceManager.GetString("MathiraiCalculatorInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenYappu.
        /// </summary>
        public static string MenYappu {
            get {
                return ResourceManager.GetString("MenYappu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenYappu, an effort to make learning Tamil grammar interesting and intuitive!.
        /// </summary>
        public static string MenyappuAnEffort {
            get {
                return ResourceManager.GetString("MenyappuAnEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenYappu has everything you need to get your foundation in Tamil grammar in a short time! All of the games, audio and video instructions on Tamil grammar are open source, free to download, and easy to use. No strings attached!.
        /// </summary>
        public static string MenyappuHasAll {
            get {
                return ResourceManager.GetString("MenyappuHasAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metreme.
        /// </summary>
        public static string Metreme {
            get {
                return ResourceManager.GetString("Metreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metreme &amp; Metrical Feet.
        /// </summary>
        public static string MetremeAndMetricalFeet {
            get {
                return ResourceManager.GetString("MetremeAndMetricalFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metreme Type.
        /// </summary>
        public static string MetremeType {
            get {
                return ResourceManager.GetString("MetremeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metreme Types.
        /// </summary>
        public static string MetremeTypes {
            get {
                return ResourceManager.GetString("MetremeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetricalFeet.
        /// </summary>
        public static string MetricalFeet {
            get {
                return ResourceManager.GetString("MetricalFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Foot Finder.
        /// </summary>
        public static string MetricalFootFinder {
            get {
                return ResourceManager.GetString("MetricalFootFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split the metremes using ‘/’ symbol. For e.g.,  you can syllable the word &quot;மனிதம்&quot; like ”மனி” / “தம்”..
        /// </summary>
        public static string MetricalFootInfoTip {
            get {
                return ResourceManager.GetString("MetricalFootInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Foot Type.
        /// </summary>
        public static string MetricalFootType {
            get {
                return ResourceManager.GetString("MetricalFootType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Foot Types.
        /// </summary>
        public static string MetricalFootTypes {
            get {
                return ResourceManager.GetString("MetricalFootTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Line.
        /// </summary>
        public static string MetricalLine {
            get {
                return ResourceManager.GetString("MetricalLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Metrical Line (requires atleast 1 Metrical Foot in that Metrical Line).
        /// </summary>
        public static string MetricalLineInfoTip {
            get {
                return ResourceManager.GetString("MetricalLineInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Line Measurer.
        /// </summary>
        public static string MetricalLineMeasurer {
            get {
                return ResourceManager.GetString("MetricalLineMeasurer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Lines.
        /// </summary>
        public static string MetricalLines {
            get {
                return ResourceManager.GetString("MetricalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Line Type.
        /// </summary>
        public static string MetricalLineType {
            get {
                return ResourceManager.GetString("MetricalLineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Line Types.
        /// </summary>
        public static string MetricalLineTypes {
            get {
                return ResourceManager.GetString("MetricalLineTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ornamentation.
        /// </summary>
        public static string Ornamentation {
            get {
                return ResourceManager.GetString("Ornamentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oranamentation Finder.
        /// </summary>
        public static string OrnamentationFinder {
            get {
                return ResourceManager.GetString("OrnamentationFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input at least 1 Metrical Line (requires atleast 2 Metrical Feet in that Metrical Line).
        /// </summary>
        public static string OrnamentationInfoTip {
            get {
                return ResourceManager.GetString("OrnamentationInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ornamentation Type.
        /// </summary>
        public static string OrnamentationType {
            get {
                return ResourceManager.GetString("OrnamentationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ornamentation Types.
        /// </summary>
        public static string OrnamentationTypes {
            get {
                return ResourceManager.GetString("OrnamentationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paa Categories.
        /// </summary>
        public static string PaaCategories {
            get {
                return ResourceManager.GetString("PaaCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paa&apos;s Sound.
        /// </summary>
        public static string PaaSound {
            get {
                return ResourceManager.GetString("PaaSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paa Types.
        /// </summary>
        public static string PaaTypes {
            get {
                return ResourceManager.GetString("PaaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse.
        /// </summary>
        public static string Parse {
            get {
                return ResourceManager.GetString("Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed Results.
        /// </summary>
        public static string ParsedResults {
            get {
                return ResourceManager.GetString("ParsedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts of Speech.
        /// </summary>
        public static string PartsOfSpeech {
            get {
                return ResourceManager.GetString("PartsOfSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosody.
        /// </summary>
        public static string Prosody {
            get {
                return ResourceManager.GetString("Prosody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        public static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer all questions and then click the &quot;Finish&quot; button to see your score..
        /// </summary>
        public static string QuizInfoTip {
            get {
                return ResourceManager.GetString("QuizInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Raja Mani.
        /// </summary>
        public static string RajaMani {
            get {
                return ResourceManager.GetString("RajaMani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhyme.
        /// </summary>
        public static string Rhyme {
            get {
                return ResourceManager.GetString("Rhyme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhyme/Alliteration Finder.
        /// </summary>
        public static string RhymeAlliterationFinder {
            get {
                return ResourceManager.GetString("RhymeAlliterationFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhyme Type.
        /// </summary>
        public static string RhymeType {
            get {
                return ResourceManager.GetString("RhymeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhyme word.
        /// </summary>
        public static string RhymeWord {
            get {
                return ResourceManager.GetString("RhymeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your score is: {1}/{2}.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second word.
        /// </summary>
        public static string SecondWord {
            get {
                return ResourceManager.GetString("SecondWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Letter Type.
        /// </summary>
        public static string SelectALetterType {
            get {
                return ResourceManager.GetString("SelectALetterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Linkage Type.
        /// </summary>
        public static string SelectALinkageType {
            get {
                return ResourceManager.GetString("SelectALinkageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Mereme Type.
        /// </summary>
        public static string SelectAMetremeType {
            get {
                return ResourceManager.GetString("SelectAMetremeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Metrical Foot Type.
        /// </summary>
        public static string SelectAMetricalFootType {
            get {
                return ResourceManager.GetString("SelectAMetricalFootType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Metrical Line Type.
        /// </summary>
        public static string SelectAMetricalLineType {
            get {
                return ResourceManager.GetString("SelectAMetricalLineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Alliteration Type.
        /// </summary>
        public static string SelectAnAlliterationType {
            get {
                return ResourceManager.GetString("SelectAnAlliterationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an End Rhyme Type.
        /// </summary>
        public static string SelectAnEndRhymeType {
            get {
                return ResourceManager.GetString("SelectAnEndRhymeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Paa with Selected Sound.
        /// </summary>
        public static string SelectAPaaWithSound {
            get {
                return ResourceManager.GetString("SelectAPaaWithSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Rhyme Type.
        /// </summary>
        public static string SelectARhymeType {
            get {
                return ResourceManager.GetString("SelectARhymeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sound Type.
        /// </summary>
        public static string SelectASound {
            get {
                return ResourceManager.GetString("SelectASound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Sound Definition                          .
        /// </summary>
        public static string SelectASoundDefinition {
            get {
                return ResourceManager.GetString("SelectASoundDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence.
        /// </summary>
        public static string Sentence {
            get {
                return ResourceManager.GetString("Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services in MenYappu.
        /// </summary>
        public static string ServicesInMenyappu {
            get {
                return ResourceManager.GetString("ServicesInMenyappu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Development.
        /// </summary>
        public static string SoftwareDevelopment {
            get {
                return ResourceManager.GetString("SoftwareDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sol Ilakkanam.
        /// </summary>
        public static string SolIlakkanam {
            get {
                return ResourceManager.GetString("SolIlakkanam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Definition.
        /// </summary>
        public static string SoundDefinition {
            get {
                return ResourceManager.GetString("SoundDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound of Paa.
        /// </summary>
        public static string SoundMatcher {
            get {
                return ResourceManager.GetString("SoundMatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After selecting a sound, choose the correct definition, paa with that sound and click on &quot;Check Answer&quot; button to see the &quot;Result&quot;..
        /// </summary>
        public static string SoundMatcherInfoTip {
            get {
                return ResourceManager.GetString("SoundMatcherInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Types.
        /// </summary>
        public static string SoundTypes {
            get {
                return ResourceManager.GetString("SoundTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start learning!.
        /// </summary>
        public static string StartLearning {
            get {
                return ResourceManager.GetString("StartLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion/Review.
        /// </summary>
        public static string SuggestionAndReview {
            get {
                return ResourceManager.GetString("SuggestionAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syllable Divider.
        /// </summary>
        public static string SyllableDivider {
            get {
                return ResourceManager.GetString("SyllableDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirukkural Analysis.
        /// </summary>
        public static string ThirukkuralAnalysis {
            get {
                return ResourceManager.GetString("ThirukkuralAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understand Poems.
        /// </summary>
        public static string UnderstandingPoems {
            get {
                return ResourceManager.GetString("UnderstandingPoems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understanding grammar helps Tamils to understand and appreciate Tamil literature!.
        /// </summary>
        public static string UnderstandingPoemsDescription {
            get {
                return ResourceManager.GetString("UnderstandingPoemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to Date.
        /// </summary>
        public static string UptoDate {
            get {
                return ResourceManager.GetString("UptoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We update the content of this portal whenever we see a new way of providing an interactive tutorial..
        /// </summary>
        public static string UptoDateDescription {
            get {
                return ResourceManager.GetString("UptoDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanjippaa.
        /// </summary>
        public static string Vanjippaa {
            get {
                return ResourceManager.GetString("Vanjippaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanjippaavinam.
        /// </summary>
        public static string Vanjippaavinam {
            get {
                return ResourceManager.GetString("Vanjippaavinam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpaa.
        /// </summary>
        public static string Venpaa {
            get {
                return ResourceManager.GetString("Venpaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpaa Conversations.
        /// </summary>
        public static string VenpaaConversations {
            get {
                return ResourceManager.GetString("VenpaaConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpaa Ruels Comparison.
        /// </summary>
        public static string VenpaaRulesComparison {
            get {
                return ResourceManager.GetString("VenpaaRulesComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpaas.
        /// </summary>
        public static string Venpaas {
            get {
                return ResourceManager.GetString("Venpaas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpaavinam.
        /// </summary>
        public static string Venpaavinam {
            get {
                return ResourceManager.GetString("Venpaavinam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vetrumai Urubugal.
        /// </summary>
        public static string VetrumaiUrubugal {
            get {
                return ResourceManager.GetString("VetrumaiUrubugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Vinod Rajan.
        /// </summary>
        public static string VinodRajan {
            get {
                return ResourceManager.GetString("VinodRajan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve got what you need!.
        /// </summary>
        public static string WeGotWhatYouNeed {
            get {
                return ResourceManager.GetString("WeGotWhatYouNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word (or) Sentence.
        /// </summary>
        public static string WordOrSentence {
            get {
                return ResourceManager.GetString("WordOrSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paa Writer.
        /// </summary>
        public static string WriteAPaa {
            get {
                return ResourceManager.GetString("WriteAPaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your favorite Tamil grammar learning portal!.
        /// </summary>
        public static string YourFavoriteTamilPortal {
            get {
                return ResourceManager.GetString("YourFavoriteTamilPortal", resourceCulture);
            }
        }
    }
}
