//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RjamSoft.Tamil.Grammar.Prosody.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProsodyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProsodyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RjamSoft.Tamil.Grammar.Prosody.Infrastructure.Resources.ProsodyResources", typeof(ProsodyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MenYappu.
        /// </summary>
        public static string AboutMenYappu {
            get {
                return ResourceManager.GetString("AboutMenYappu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenYappu is a website that has all the services essential for poem writers like spell checker/corrector, prosody games, poem composer and poem analyzer integrated and presented in a very simple, intuitive user interface. Since the services are also exposed as web services, mobile phone users can write an app in their preferred platforms like Apple IOS, Android or Windows Mobile usiing these web services and consume them..
        /// </summary>
        public static string AboutMenYappuDetails {
            get {
                return ResourceManager.GetString("AboutMenYappuDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliteration.
        /// </summary>
        public static string Alliteration {
            get {
                return ResourceManager.GetString("Alliteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asiriyappaa.
        /// </summary>
        public static string Asiriyappaa {
            get {
                return ResourceManager.GetString("Asiriyappaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asiriyappaavinam.
        /// </summary>
        public static string Asiriyappaavinam {
            get {
                return ResourceManager.GetString("Asiriyappaavinam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Bogdan Urs.
        /// </summary>
        public static string BogdanUrs {
            get {
                return ResourceManager.GetString("BogdanUrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Answer.
        /// </summary>
        public static string CheckAnswer {
            get {
                return ResourceManager.GetString("CheckAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button for help.
        /// </summary>
        public static string ClickThisButtonForHelp {
            get {
                return ResourceManager.GetString("ClickThisButtonForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with Venpaa rules.
        /// </summary>
        public static string CompareWithVenpaaRules {
            get {
                return ResourceManager.GetString("CompareWithVenpaaRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Duration Count.
        /// </summary>
        public static string CorrectDurationCount {
            get {
                return ResourceManager.GetString("CorrectDurationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not parse short-u before initial vowels.
        /// </summary>
        public static string DoNotParseShortUBeforeInitialVowels {
            get {
                return ResourceManager.GetString("DoNotParseShortUBeforeInitialVowels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Count.
        /// </summary>
        public static string DurationCount {
            get {
                return ResourceManager.GetString("DurationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimiate Vilaankaay Metrica Feet.
        /// </summary>
        public static string EliminateVilaankaayMetricalFeet {
            get {
                return ResourceManager.GetString("EliminateVilaankaayMetricalFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Rhyme.
        /// </summary>
        public static string EndRhyme {
            get {
                return ResourceManager.GetString("EndRhyme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Duration Count and click on &quot;Check Answer&quot; button to see the &quot;Result&quot;. .
        /// </summary>
        public static string EnterDurationCountAndCheckResult {
            get {
                return ResourceManager.GetString("EnterDurationCountAndCheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executor.
        /// </summary>
        public static string Executor {
            get {
                return ResourceManager.GetString("Executor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you enter the answer(s), click on &quot;Check Answer&quot; button to see the &quot;Result&quot;..
        /// </summary>
        public static string HowToSeeTheResult {
            get {
                return ResourceManager.GetString("HowToSeeTheResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Verse.
        /// </summary>
        public static string InputTheVerse {
            get {
                return ResourceManager.GetString("InputTheVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Word.
        /// </summary>
        public static string InputWord {
            get {
                return ResourceManager.GetString("InputWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiration/Motivation.
        /// </summary>
        public static string InspirationAndMotivation {
            get {
                return ResourceManager.GetString("InspirationAndMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalippaa.
        /// </summary>
        public static string Kalippaa {
            get {
                return ResourceManager.GetString("Kalippaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalippaavinam.
        /// </summary>
        public static string Kalippaavinam {
            get {
                return ResourceManager.GetString("Kalippaavinam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Kandasamy Palanisamy.
        /// </summary>
        public static string KandasamyPalanisamy {
            get {
                return ResourceManager.GetString("KandasamyPalanisamy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Type Finder.
        /// </summary>
        public static string LetterTypeFinder {
            get {
                return ResourceManager.GetString("LetterTypeFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either enter only one word (or) click on &quot;Sample&quot; button below..
        /// </summary>
        public static string LetterTypeFinderInfoTip {
            get {
                return ResourceManager.GetString("LetterTypeFinderInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Types.
        /// </summary>
        public static string LetterTypes {
            get {
                return ResourceManager.GetString("LetterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkage.
        /// </summary>
        public static string Linkage {
            get {
                return ResourceManager.GetString("Linkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkage Finder.
        /// </summary>
        public static string LinkageFinder {
            get {
                return ResourceManager.GetString("LinkageFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathirai Calculator.
        /// </summary>
        public static string MathiraiCalculator {
            get {
                return ResourceManager.GetString("MathiraiCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter only one word (or) sentence (or) click on &quot;Sample&quot; button below..
        /// </summary>
        public static string MathiraiCalculatorInfoTip {
            get {
                return ResourceManager.GetString("MathiraiCalculatorInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenYappu.
        /// </summary>
        public static string MenYappu {
            get {
                return ResourceManager.GetString("MenYappu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metreme.
        /// </summary>
        public static string Metreme {
            get {
                return ResourceManager.GetString("Metreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metreme &amp; Metrical Feet.
        /// </summary>
        public static string MetremeAndMetricalFeet {
            get {
                return ResourceManager.GetString("MetremeAndMetricalFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetricalFeet.
        /// </summary>
        public static string MetricalFeet {
            get {
                return ResourceManager.GetString("MetricalFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Foot Finder.
        /// </summary>
        public static string MetricalFootFinder {
            get {
                return ResourceManager.GetString("MetricalFootFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Line.
        /// </summary>
        public static string MetricalLine {
            get {
                return ResourceManager.GetString("MetricalLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Line Measurer.
        /// </summary>
        public static string MetricalLineMeasurer {
            get {
                return ResourceManager.GetString("MetricalLineMeasurer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ornamentation.
        /// </summary>
        public static string Ornamentation {
            get {
                return ResourceManager.GetString("Ornamentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oranamentation Finder.
        /// </summary>
        public static string OrnamentationFinder {
            get {
                return ResourceManager.GetString("OrnamentationFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paa Categories.
        /// </summary>
        public static string PaaCategories {
            get {
                return ResourceManager.GetString("PaaCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paa Types.
        /// </summary>
        public static string PaaTypes {
            get {
                return ResourceManager.GetString("PaaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse.
        /// </summary>
        public static string Parse {
            get {
                return ResourceManager.GetString("Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed Results.
        /// </summary>
        public static string ParsedResults {
            get {
                return ResourceManager.GetString("ParsedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosody.
        /// </summary>
        public static string Prosody {
            get {
                return ResourceManager.GetString("Prosody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Raja Mani.
        /// </summary>
        public static string RajaMani {
            get {
                return ResourceManager.GetString("RajaMani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhyme.
        /// </summary>
        public static string Rhyme {
            get {
                return ResourceManager.GetString("Rhyme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhyme/Alliteration Finder.
        /// </summary>
        public static string RhymeAlliterationFinder {
            get {
                return ResourceManager.GetString("RhymeAlliterationFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Letter Type.
        /// </summary>
        public static string SelectALetterType {
            get {
                return ResourceManager.GetString("SelectALetterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Development.
        /// </summary>
        public static string SoftwareDevelopment {
            get {
                return ResourceManager.GetString("SoftwareDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion/Review.
        /// </summary>
        public static string SuggestionAndReview {
            get {
                return ResourceManager.GetString("SuggestionAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syllable Divider.
        /// </summary>
        public static string SyllableDivider {
            get {
                return ResourceManager.GetString("SyllableDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanjippaa.
        /// </summary>
        public static string Vanjippaa {
            get {
                return ResourceManager.GetString("Vanjippaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanjippaavinam.
        /// </summary>
        public static string Vanjippaavinam {
            get {
                return ResourceManager.GetString("Vanjippaavinam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpaa.
        /// </summary>
        public static string Venpaa {
            get {
                return ResourceManager.GetString("Venpaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpaa Conversations.
        /// </summary>
        public static string VenpaaConversations {
            get {
                return ResourceManager.GetString("VenpaaConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpaa Ruels Comparison.
        /// </summary>
        public static string VenpaaRulesComparison {
            get {
                return ResourceManager.GetString("VenpaaRulesComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpaas.
        /// </summary>
        public static string Venpaas {
            get {
                return ResourceManager.GetString("Venpaas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpaavinam.
        /// </summary>
        public static string Venpaavinam {
            get {
                return ResourceManager.GetString("Venpaavinam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Vinod Rajan.
        /// </summary>
        public static string VinodRajan {
            get {
                return ResourceManager.GetString("VinodRajan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word (or) Sentence.
        /// </summary>
        public static string WordOrSentence {
            get {
                return ResourceManager.GetString("WordOrSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paa Writer.
        /// </summary>
        public static string WriteAPaa {
            get {
                return ResourceManager.GetString("WriteAPaa", resourceCulture);
            }
        }
    }
}
