//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RjamSoft.Tamil.Grammar.Prosody.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProsodyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProsodyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RjamSoft.Tamil.Grammar.Prosody.Infrastructure.Resources.ProsodyResources", typeof(ProsodyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MenYappu.
        /// </summary>
        public static string AboutMenYappu {
            get {
                return ResourceManager.GetString("AboutMenYappu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliteration.
        /// </summary>
        public static string Alliteration {
            get {
                return ResourceManager.GetString("Alliteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare with Venpa rules.
        /// </summary>
        public static string CompareWithVenpaRules {
            get {
                return ResourceManager.GetString("CompareWithVenpaRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not parse short-u before initial vowels.
        /// </summary>
        public static string DoNotParseShortUBeforeInitialVowels {
            get {
                return ResourceManager.GetString("DoNotParseShortUBeforeInitialVowels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimiate Vilaankaay Metrica Feet.
        /// </summary>
        public static string EliminateVilaankaayMetricalFeet {
            get {
                return ResourceManager.GetString("EliminateVilaankaayMetricalFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Rhyme.
        /// </summary>
        public static string EndRhyme {
            get {
                return ResourceManager.GetString("EndRhyme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Verse.
        /// </summary>
        public static string InputTheVerse {
            get {
                return ResourceManager.GetString("InputTheVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Type Finder.
        /// </summary>
        public static string LetterTypeFinder {
            get {
                return ResourceManager.GetString("LetterTypeFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkage.
        /// </summary>
        public static string Linkage {
            get {
                return ResourceManager.GetString("Linkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkage Finder.
        /// </summary>
        public static string LinkageFinder {
            get {
                return ResourceManager.GetString("LinkageFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathirai Calculator.
        /// </summary>
        public static string MathiraiCalculator {
            get {
                return ResourceManager.GetString("MathiraiCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenYappu.
        /// </summary>
        public static string MenYappu {
            get {
                return ResourceManager.GetString("MenYappu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metreme &amp; Metrical Feet.
        /// </summary>
        public static string MetremeAndMetricalFeet {
            get {
                return ResourceManager.GetString("MetremeAndMetricalFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Foot Finder.
        /// </summary>
        public static string MetricalFootFinder {
            get {
                return ResourceManager.GetString("MetricalFootFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Line.
        /// </summary>
        public static string MetricalLine {
            get {
                return ResourceManager.GetString("MetricalLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical Line Measurer.
        /// </summary>
        public static string MetricalLineMeasurer {
            get {
                return ResourceManager.GetString("MetricalLineMeasurer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oranamentation Finder.
        /// </summary>
        public static string OrnamentationFinder {
            get {
                return ResourceManager.GetString("OrnamentationFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse.
        /// </summary>
        public static string Parse {
            get {
                return ResourceManager.GetString("Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed Results.
        /// </summary>
        public static string ParsedResults {
            get {
                return ResourceManager.GetString("ParsedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhyme.
        /// </summary>
        public static string Rhyme {
            get {
                return ResourceManager.GetString("Rhyme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhyme/Alliteration Finder.
        /// </summary>
        public static string RhymeAlliterationFinder {
            get {
                return ResourceManager.GetString("RhymeAlliterationFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syllable Divider.
        /// </summary>
        public static string SyllableDivider {
            get {
                return ResourceManager.GetString("SyllableDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpa Conversations.
        /// </summary>
        public static string VenpaConversations {
            get {
                return ResourceManager.GetString("VenpaConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpa Ruels Comparison.
        /// </summary>
        public static string VenpaRulesComparison {
            get {
                return ResourceManager.GetString("VenpaRulesComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venpas.
        /// </summary>
        public static string Venpas {
            get {
                return ResourceManager.GetString("Venpas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paa Writer.
        /// </summary>
        public static string WriteAPaa {
            get {
                return ResourceManager.GetString("WriteAPaa", resourceCulture);
            }
        }
    }
}
